POST http://localhost:8080/pet
Content-Type: application/json

{
  "category": {
    "id": 2
  },
  "tags": [
    {
      "id": 2
    },
    {
      "id": 3
    }
  ],
  "name": "doggie",
  "status": "available"
}

###

PUT http://localhost:8080/pet
Content-Type: application/json

{
  "category": {
    "id": 3
  },
  "name": "doggie2",
   "tags": [
    {
      "id": 1
    }
  ],
  "status": "available"
}

###

GET http://localhost:8080/pet/findByStatus?status=available
Content-Type: application/json

###

GET http://localhost:8080/pet/lk
Content-Type: application/json

###

POST http://localhost:8080/pet/1
Content-Type: application/json

{
  "name": "bobik",
  "status": "sold"
}

###

DELETE http://localhost:8080/pet/2
Content-Type: application/json

###

POST http://localhost:8081/store/order
Content-Type: application/json

{
  "id": 0,
  "petId": 0,
  "quantity": 0,
  "shipDate": "2020-07-14T13:28:01.814Z",
  "status": "placed",
  "complete": true
}

###

POST http://localhost:8080/user/createWithList
Content-Type: application/json

  {
    "userName": "Dod",
    "firstName": "string",
    "lastName": "string",
    "email": "string",
    "password": "string",
    "phone": "string",
    "userStatus": 0
  }

###

GET http://localhost:8080/user/login?password=string&userName=Dod
Content-Type: application/json

###

GET http://localhost:8080/user/Dod
Content-Type: application/json
token:f0ad3b38-e99f-4b6c-abd4-82e8cc40fc85

###







